### ISSUE TITLE
Support passing environment variables

### ISSUE THREAD

**Issue by raakasf** [magefile/mage-action#216]
As Mage currently does not support positional args (https://github.com/magefile/mage/issues/170 or https://github.com/magefile/mage/issues/24) we use environment variables with mage. Could you please add passing environment variables with this action?

**Comment by crazy-max** [comment]
@raakasf You can already do that with GitHub Actions:

```yaml
      -
        name: Run Mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
        env:
          MYENV: value
```
