### ISSUE TITLE
Mage Github action appears to download mage on every run without caching

### ISSUE THREAD

**Issue by joshuacc** [magefile/mage-action#264]
#### Steps to reproduce this issue

1. Set up a Github action that includes the mage action as a step
2. Run the action multiple times

#### Expected behaviour

It should download mage on the first run, but not subsequent runs.

#### Actual behaviour

It downloads mage on every run.

I believe this is because the action never attempts to check if the mage executable is in the cache and skip the download if available. The [`tc.find()` method](https://github.com/actions/toolkit/tree/main/packages/tool-cache#find) is never invoked in the installer.

### Configuration

* Repository URL (if public): https://github.com/joshuacc/ahkpm/
* Build URL (if public): https://github.com/joshuacc/ahkpm/actions/runs/3353106807/jobs/5555688325

```yml
name: mage
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build:
    name: mage build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Run Mage
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: verify
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

### Logs

[logs_104.zip](https://github.com/magefile/mage-action/files/9894714/logs_104.zip)
