### ISSUE TITLE
Possible issues with latest version on self hosted runners

### ISSUE THREAD

**Issue by cep21** [magefile/mage-action#297]
Our mage actions stopped working with the latest release.  Here is the log:

```
Mage version found: v1.15.0
Received 0 of 1494228 (0.0%), 0.0 MBs/sec
Cache Size: ~1 MB (1494228 B)
/usr/bin/tar -xf /runner/_work/_temp/4fca178b-b25d-4ed8-84c4-940eb84309da/cache.tzst -P -C /runner/_work/config/config --use-compress-program unzstd
Cache restored successfully
Restored mage-action-cache-1.[15](https://github.com/X/Y/actions/runs/6027441474/job/16352649576?pr=42785#step:12:16).0 from GitHub actions cache
Error: ENOENT: no such file or directory, stat '/home/runner/.mage'
Received 1494228 of 1494228 (100.0%), 0.7 MBs/sec
```

From this workflow file:
```
      - name: Sync staging
        uses: magefile/mage-action@v2
        with:
          args: <private>
```

It's possible the restore is broken if the runner is self hosted?
