### ISSUE TITLE
incorrect release URL for macOS (darwin) runners

### ISSUE THREAD

**Issue by na4ma4** [magefile/mage-action#332]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/mage/mage-action/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using the action on a macOS runner it will fail to download the release binary.

### Expected behaviour

For the action to download the correct binary.

### Actual behaviour

```
Run magefile/mage-action@v3
Mage version found: v1.1[5](https://github.com/na4ma4/mage-macos-issue/actions/runs/9638247781/job/26578654439#step:4:6).0
Downloading https://github.com/magefile/mage/releases/download/v1.15.0/mage_1.15.0_macOS-ARM[6](https://github.com/na4ma4/mage-macos-issue/actions/runs/9638247781/job/26578654439#step:4:7)4.tar.gz...
Error: Unexpected HTTP response: 404
```

### Steps to reproduce

1. Use magefile/mage-action in workflow.
2. `runs-on: macos-latest`
3. step will fail

### Repository URL

https://github.com/na4ma4/mage-macos-issue

### Workflow run URL

https://github.com/na4ma4/mage-macos-issue/actions/runs/9638284485

### YAML workflow

```yaml
name: "GoReleaser"

on:
  push:
  workflow_dispatch:


jobs:
  mage-test:
    name: "Mage Test: ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: ^1
      id: go

    - name: Run Mage
      uses: magefile/mage-action@v3
```

### Workflow logs

[logs_25224800589.zip](https://github.com/user-attachments/files/15948860/logs_25224800589.zip)
